CREATE TABLE TAUTHORITIES (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) ,
	CONSTRAINT TAUTHORITIES_PKEY PRIMARY KEY (ID)
);

INSERT INTO TAUTHORITIES (NAME) VALUES ('ROLE_USER');
INSERT INTO TAUTHORITIES (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO TAUTHORITIES (NAME) VALUES ('ROLE_GERENTE');

CREATE TABLE TUSERSAUTHORITIES (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	USERID INTEGER NOT NULL,
	AUTHORITIEID INTEGER NOT NULL,
	CONSTRAINT TUSERSAUTHORITIES_PKEY PRIMARY KEY (ID)
);
